---
apiVersion: v1
kind: Service
metadata:
  name:
    '{ include "helm.fullname" . }': null
  labels:
    '{ include "helm.labels" . | nindent 4 }': null
spec:
  type:
    "{ .Values.service.type }": null
  ports:
    - port:
        "{ .Values.service.port }": null
      targetPort: http
      protocol: TCP
      name: http
  selector:
    '{ include "helm.selectorLabels" . | nindent 4 }': null
